name: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  pypi-publish:
    name: build and upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        
      - name: Install dependencies and pdm
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://pdm-project.org/install-pdm.py | python3 -

      - name: Build package
        run: pdm build -v
        
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1